version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "peter"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5      

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8060:8080

  web:
    build: .
    ports:
      - "8080:5000"

    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "peter"
      POSTGRES_DATABASE: "postgres"
      POSTGRES_HOSTNAME: "db"
      LIMIT_ITEMS: 500

    depends_on:
      db:
        condition: service_healthy
